### ISSUE TITLE
Confused on how this scales

### ISSUE THREAD

**Issue by matbeedotcom** [siphontv/p2ptv#2]
I haven't gone through the source code, but how exactly is this scaling? Is it WebRTC nodes transferring data to each other, or is it multiple servers serving the data through webrtc?

**Comment by eadle** [comment]
The idea was to assemble clients into a P2P delivery structure such as an mtreebone, so the users do most of the video distribution. This hasn't been implemented and currently the gateway sends video directly to each connected peer. The delivery network is where the man hours are needed. I may edit the README to make the state of the project more obvious.

There's a few commented out lines in p2ptv.js that inserts peers into a linked-list. :^)

**Comment by matbeedotcom** [comment]
Would it make sense to match peers based on a DHT? So--connecting users through this hash table, like a Torrent.

**Comment by eadle** [comment]
WebRTC peer connections rely on a signaling server to negotiate connections, so the benefit of distributed hash tables might be lost, no?

Are you interested in livestreaming torrents?

**Comment by matbeedotcom** [comment]
Well, livestreaming personal media being transferred over torrent protocol. Interested in having quality-switching behavior for magnet URI's.

**Comment by eadle** [comment]
My bad. I assume you mean using Webtorrent to download sequential chunks and then distribute the chunks to your livestream users. Quality switching would require several different transcodes using FFmpeg. So you would have a Webtorrent user form a peer connection with a server that would transcode the chunks in realtime and have each FFmpeg output be passed to the appropriate p2ptv instance (ie. 144p, 240p, 360p, 480p) then deliver that way.

Unless you mean just using standard BitTorrent protocol, but there  wouldn't be much of a difference.

**Comment by matbeedotcom** [comment]
As a start, quality-switching is out of the question. Currently, each keyframe is being encoded on the fly as its own video segment. I would like to see an on-the-fly quality change. Source, remaining as a Torrent, and the video chunks being cached and served through the torrent network.

I'm imagining, essentially, a video being encoded to multiple resolutions through a somewhat large network. Then the video segments served over Torrent.

**Comment by eadle** [comment]
From the users perspective, is it a livestream or VOD?

**Comment by matbeedotcom** [comment]
From the users perspective, VOD.

**Comment by matbeedotcom** [comment]
But, imagine an HLS playlist, but with references to Magnet URI's rather than HTTP urls

**Comment by eadle** [comment]
Hmm... I get what you're trying to do, but this project isn't really about VOD. Are you thinking about forking this project as a foundation or do you have a repository already?

**Comment by matbeedotcom** [comment]
Yeah, was just curious how you were planning on scaling through webrtc.

**Comment by eadle** [comment]
Oh okay. When a p2ptv node (A) has too many peer connections, a new p2ptv node (B) is created. B becomes the child of A and the chunks are pushed from A to B. New peers connect with B. The transcoding is only done at one server. It would also be possible to just send the trancoding directly to each p2ptv node and have no parent-child relationships between them.

P2PTV and VOD are so different though.

**Comment by eadle** [comment]
Okay... I have a crazy idea that just might work for your project...

**Comment by matbeedotcom** [comment]
Do you have Gitter?

**Comment by eadle** [comment]
What's that?

**Comment by matbeedotcom** [comment]
Chat system for github users. Create an account and I'll invite.

**Comment by eadle** [comment]
Yeah, I just set it up. Now what?
