### ISSUE TITLE
bug in npm install?

### ISSUE THREAD

**Issue by kraja** [siphontv/p2ptv#5]
Hi,
have i anything bad, please?

![image](https://cloud.githubusercontent.com/assets/125937/13597360/6b1496a0-e518-11e5-90e2-c82def725b39.png)

**Comment by ralyodio** [comment]
what version of node, what os? type `node -v`

**Comment by kraja** [comment]
Thank you for fast reply Anthony.

I testing on Debian 8.3 (jessie) 64bit
node v5.7.1

**Comment by eadle** [comment]
Hey @kraja, sorry for the slow reply. Did you end up getting it working? I have it working with v5.7.1 with Wheezy, and it was developed on Jessie, so it should work.
